import { ClaimFormData, DocumentType } from "@/types";
import PDFDocument from "pdfkit";

export function generateDocument(
  claim: ClaimFormData,
  documentType: DocumentType
): Buffer {
  const doc = new PDFDocument({ margin: 50 });
  const buffers: Buffer[] = [];

  doc.on("data", (chunk) => buffers.push(chunk));

  // Header
  doc.fontSize(24).font("Helvetica-Bold").text("Stop the Slop");
  doc.moveDown(0.5);
  doc.fontSize(10)
    .font("Helvetica")
    .text("Professional Legal Document", { align: "left" });
  doc.moveDown(1);

  // Document title based on type
  const titles = {
    complaint: "Complaint Letter",
    regulatory: "Regulatory Complaint",
    "letter-before-action": "Letter Before Action",
  };

  doc.fontSize(18).font("Helvetica-Bold").text(titles[documentType]);
  doc.moveDown(1);

  // Date
  doc.fontSize(11).text(`Date: ${new Date().toLocaleDateString()}`);
  doc.moveDown(1);

  // To section
  doc.fontSize(11).font("Helvetica-Bold").text("To:");
  doc.font("Helvetica").text(claim.companyName);
  if (claim.companyWebsite) {
    doc.text(claim.companyWebsite);
  }
  if (claim.companyCountry) {
    doc.text(`Country: ${claim.companyCountry}`);
  }
  doc.moveDown(1);

  // Subject
  doc.fontSize(11).font("Helvetica-Bold").text("Subject: Complaint Regarding AI-Generated Content");
  doc.moveDown(1);

  // Body
  doc.fontSize(11).font("Helvetica");

  const letterBody = getLetterBody(claim, documentType);
  doc.text(letterBody, { align: "justify" });

  doc.moveDown(1);

  // Closing based on document type
  if (documentType === "letter-before-action") {
    doc.text(
      "Please advise us of your response within 14 days of receipt of this letter.",
      { align: "justify" }
    );
    doc.moveDown(1);
    doc.text(
      "Yours faithfully,",
      { align: "left" }
    );
  } else {
    doc.text("We look forward to your prompt response.", { align: "justify" });
    doc.moveDown(1);
    doc.text("Best regards,", { align: "left" });
  }

  doc.moveDown(2);
  doc.text("___________________________");
  doc.moveDown(0.5);
  doc.text("[Your Name]");

  // Finalize
  doc.end();

  return Buffer.concat(buffers);
}

function getLetterBody(claim: ClaimFormData, documentType: DocumentType): string {
  const contentTypeLabel = claim.contentType.charAt(0).toUpperCase() + claim.contentType.slice(1);
  const exposureDate = new Date(claim.exposureDate).toLocaleDateString();

  const baseBody = `We are writing to lodge a formal ${documentType === "complaint" ? "complaint" : documentType === "regulatory" ? "regulatory complaint" : "notice"} regarding the publication and distribution of undisclosed AI-generated content on your platform.

On ${exposureDate}, we were exposed to ${contentTypeLabel.toLowerCase()} content that was generated by artificial intelligence without clear disclosure to users. This content was presented in a manner that could reasonably be mistaken for human-created material, thereby violating consumer protection regulations and the principles of transparency required by EU law.

Incident Details:
${claim.incidentDescription}

Disclosure Status:
You disclosed that the content was AI-generated: ${claim.hadDisclosure === "yes" ? "Yes" : "No"}
${claim.disclosureDetails ? `Additional details: ${claim.disclosureDetails}` : ""}

This failure to clearly disclose the use of artificial intelligence constitutes a breach of consumer protection obligations under EU Directive 2005/29/EC (Unfair Commercial Practices Directive) and potentially violates the Digital Services Act requirements for algorithmic transparency.

We request that you:
1. Immediately remove or clearly label the AI-generated content in question
2. Implement clear, conspicuous disclosure mechanisms for all AI-generated content on your platform
3. Provide documentation of the measures you will take to prevent similar violations in the future

${documentType === "regulatory" ? "This complaint will also be filed with the relevant regulatory authorities to ensure compliance with EU consumer protection laws." : ""}

${documentType === "letter-before-action" ? "Please note that failure to respond satisfactorily to this notice may result in formal legal proceedings to recover damages and seek injunctive relief." : ""}`;

  return baseBody;
}

export function getDocumentFilename(
  documentType: DocumentType
): string {
  const names = {
    complaint: "complaint-letter",
    regulatory: "regulatory-complaint",
    "letter-before-action": "letter-before-action",
  };
  return `${names[documentType]}-${Date.now()}.pdf`;
}
